## ***Numpy***

In [1]:
import numpy as np

In [2]:
li = [10,20,30,40]

type(li)

list

##### How to create an array

In [3]:
arr = np.array(li)
arr

array([10, 20, 30, 40])

In [4]:
type(arr) #nd below denotes number and dimensions

numpy.ndarray

In [5]:
# to check number of dimension in array

arr.ndim

1

In [6]:
# to check number of shape in array

arr.shape

(4,)

In [7]:
# to check number of size in array

arr.size

4

In [8]:
# 2D Array

arr2d = np.array([[10,20,30,40]])
arr2d

array([[10, 20, 30, 40]])

In [9]:
#no. of dimension

arr2d.ndim

2

In [10]:
#shape of array

arr2d.shape

(1, 4)

In [11]:
#no. of elements

arr2d.size

4

In [12]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(3, 3)

In [15]:
arr2.size

9

In [16]:
#3D array

arr3d = np.array([[[1,2,3,4]]])
arr3d

array([[[1, 2, 3, 4]]])

In [17]:
arr3d.ndim

3

In [18]:
arr3d.shape

(1, 1, 4)

In [19]:
arr3d.size

4

In [20]:
arr3 = np.array([[[1,2],[3,4],[6,7]],[[3,4],[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4],
        [6, 7]],

       [[3, 4],
        [5, 6],
        [7, 8]]])

In [21]:
arr3.shape

(2, 3, 2)

##### Reshape()

In [22]:
arr1d = np.array([1,2,3,4,5,6])
arr1d

array([1, 2, 3, 4, 5, 6])

In [23]:
arr1d.shape

(6,)

In [24]:
arr2d = arr1d.reshape(2,3) #(2,3) (1,6)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2d.shape

(2, 3)

In [118]:
arr3d = arr1d.reshape(3,2,1)
arr3d

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [27]:
arr3d.shape

(2, 3, 1)

In [28]:
arr3d.ndim

3

In [29]:
arr3d.size

6

### **ravel() or flatten()** converts any array into 1D array

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
#2d array to 1D

np.ravel(arr2d)

array([1, 2, 3, 4, 5, 6])

In [32]:
#3D array to 1D

np.ravel(arr3d)

array([1, 2, 3, 4, 5, 6])

In [33]:
arr1d

array([1, 2, 3, 4, 5, 6])

In [34]:
#accessing first element in array

arr1d[0]

np.int64(1)

In [35]:
#accessing last element in array

arr1d[-1]

np.int64(6)

In [36]:
#first two elements

arr1d[0:2]

array([1, 2])

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
#display first row

arr2d[0]

array([1, 2, 3])

In [39]:
#display number 2 from the array

arr2d[0,1]

np.int64(2)

In [40]:
#display 5 & 6

arr2d[1,-2:] # this can be done in multiple ways like arr2d[1,1:]

array([5, 6])

In [41]:
#example

arr2d[1,1:]

array([5, 6])

In [42]:
arr3d

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [43]:
#display first column with 3 rows

arr3d[0]

array([[1],
       [2],
       [3]])

In [44]:
#display 1 from first row

arr3d[0,0]

array([1])

In [45]:
arr2d.max()

np.int64(6)

In [46]:
arr2d.min()

np.int64(1)

In [47]:
arr3d.max()

np.int64(6)

In [48]:
arr1d

array([1, 2, 3, 4, 5, 6])

In [49]:
#multiply with 10 to arr1d

arr1d*10

array([10, 20, 30, 40, 50, 60])

In [50]:
#multiply list with 10

li = [1,2,3,4,5,6]

[i*10 for i in li] # 4 iteration

[10, 20, 30, 40, 50, 60]

In [51]:
#total of arr1d

np.sum(arr1d)

np.int64(21)

In [52]:
arr2d*100

array([[100, 200, 300],
       [400, 500, 600]])

In [53]:
arr2d/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
#if we want to perform a function with a single row

arr2d[0]*10

array([10, 20, 30])

In [56]:
#if we want to perform a function with a single element in single row

arr2d[0,1:]*10

array([20, 30])

In [57]:
#selecting specific column - select all rows first always

arr2d[:,0]

array([1, 4])

In [58]:
#reverse rows

arr2d[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [59]:
#reverse columns

arr2d[:,::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [60]:
#transpose() converts rows to columns and columns to rows

arr2d.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
# display value above 4

arr2d[arr2d>4]

array([5, 6])

In [62]:
arr1d

array([1, 2, 3, 4, 5, 6])

In [63]:
arr1d[arr1d>4]

array([5, 6])

In [64]:
li = list(range(10))  #range function used to create a range for the value provided
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
#creating array using range function

arr2 = np.array(range(10,22))
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [66]:
arr2.shape

(12,)

In [67]:
arr2_ = np.array(range(10,22)).reshape(3,4) # reshaping the array
arr2_

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [68]:
#display elements above 15 (filtering)

arr2_[arr2_>15]

array([16, 17, 18, 19, 20, 21])

In [69]:
arr2_

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [70]:
#convert values into true and false

np.where(arr2_>15,True,False)

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
np.where(arr2_%2==0,"Even","Odd")

array([['Even', 'Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even', 'Odd']], dtype='<U4')

In [72]:
arr2_

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [73]:
type(arr2_)

numpy.ndarray

In [74]:
#dataype of values in an array

arr2_.dtype

dtype('int64')

In [75]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [76]:
np.where(arr2_%2==0,"Even","Odd")

array([['Even', 'Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even', 'Odd']], dtype='<U4')

In [77]:
def axb(a,b):
  return a+b

In [78]:
axb(10,20)

30

In [79]:
axb(15,99)

114

In [123]:
#2d array creation

wsd = np.array([[10,20,30],[40,50,60]])

wsd

array([[10, 20, 30],
       [40, 50, 60]])

In [83]:
wsd.shape

(2, 3)

In [84]:
fsx = np.array([10,20,30])
fsx

array([10, 20, 30])

In [94]:
# now add fsx to wsd 1D to 2D arrays

add = wsd+fsx

In [95]:
add

array([[20, 40, 60],
       [50, 70, 90]])

In [96]:
arr3d

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [97]:
arr3d.shape

(2, 3, 1)

In [124]:
#creating a 3d array from an existing 2d array

arr3 = wsd.reshape(3,2,1)

arr3

array([[[10],
        [20]],

       [[30],
        [40]],

       [[50],
        [60]]])