## ***Numpy***

In [ ]:
import numpy as np

In [ ]:
li = [10,20,30,40]

type(li)

list

##### How to create an array

In [ ]:
arr = np.array(li)
arr

array([10, 20, 30, 40])

In [ ]:
type(arr) #nd below denotes number and dimensions

numpy.ndarray

In [ ]:
# to check number of dimension in array

arr.ndim

1

In [ ]:
# to check number of shape in array

arr.shape

(4,)

In [ ]:
# to check number of size in array

arr.size

4

In [ ]:
# 2D Array

arr2d = np.array([[10,20,30,40]])
arr2d

array([[10, 20, 30, 40]])

In [ ]:
#no. of dimension

arr2d.ndim

2

In [ ]:
#shape of array

arr2d.shape

(1, 4)

In [ ]:
#no. of elements

arr2d.size

4

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr2.size

9

In [ ]:
#3D array

arr3d = np.array([[[1,2,3,4]]])
arr3d

array([[[1, 2, 3, 4]]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(1, 1, 4)

In [ ]:
arr3d.size

4

In [ ]:
arr3 = np.array([[[1,2],[3,4],[6,7]],[[3,4],[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4],
        [6, 7]],

       [[3, 4],
        [5, 6],
        [7, 8]]])

In [ ]:
arr3.shape

(2, 3, 2)

##### Reshape()

In [ ]:
arr1d = np.array([1,2,3,4,5,6])
arr1d

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1d.shape

(6,)

In [38]:
arr2d = arr1d.reshape(2,3) #(2,3) (1,6)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr2d.shape

(2, 3)

In [40]:
arr3d = arr1d.reshape(2,3,1)
arr3d

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [41]:
arr3d.shape

(2, 3, 1)

In [35]:
arr3d.ndim

3

In [36]:
arr3d.size

6

### **ravel() or flatten()** converts any array into 1D array

In [42]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
#2d array to 1D

np.ravel(arr2d)

array([1, 2, 3, 4, 5, 6])

In [49]:
#3D array to 1D

np.ravel(arr3d)

array([1, 2, 3, 4, 5, 6])

In [50]:
arr1d

array([1, 2, 3, 4, 5, 6])

In [53]:
#accessing first element in array

arr1d[0]

np.int64(1)

In [54]:
#accessing last element in array

arr1d[-1]

np.int64(6)

In [55]:
#first two elements

arr1d[0:2]

array([1, 2])

In [56]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#display first row

arr2d[0]

array([1, 2, 3])

In [60]:
#display number 2 from the array

arr2d[0,1]

np.int64(2)

In [64]:
#display 5 & 6

arr2d[1,-2:] # this can be done in multiple ways like arr2d[1,1:]

array([5, 6])

In [66]:
#example

arr2d[1,1:]

array([5, 6])

In [67]:
arr3d

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [77]:
#display first column with 3 rows

arr3d[0]

array([[1],
       [2],
       [3]])

In [76]:
#display 1 from first row

arr3d[0,0]

array([1])

In [79]:
arr2d.max()

np.int64(6)

In [80]:
arr2d.min()

np.int64(1)

In [81]:
arr3d.max()

np.int64(6)